/* eslint-disable import/no-anonymous-default-export */
export default {
    ADD_RECORD: 'ADD_RECORD',
    LOAD_RECORDS: 'LOAD_RECORDS',
    CITY_FILTER: 'CITY_FILTER',
    DATE_FILTER: 'DATE_FILTER',
    FORECASTDATE_FILTER: 'FORECASTDATE_FILTER',
    LOAD_FORECAST_RECORDS: 'LOAD_FORECAST_RECORDS',
    LOAD_WARNING_RXJS: 'LOAD_WARNING_RXJS',
    FILTER_WARNING_RXJS: 'FILTER_WARNING_RXJS',
    GET_UPDATES_SINCE_LAST: 'GET_UPDATES_SINCE_LAST',
    LOAD_SOCKET_RECORDS: 'LOAD_SOCKET_RECORDS',
    FILTER_WARNING_SOCKET: 'FILTER_WARNING_SOCKET'
} 